dataset:
  filepath: "data/penguins_size.csv"
  target_column: "species"
  null_values: ["NA", "."]

preprocessing:
  categorical_features: ["island", "sex"]
  numeric_features:
    - "culmen_length_mm"
    - "culmen_depth_mm"
    - "flipper_length_mm"
    - "body_mass_g"
  fill_strategy: "median"

# This configuration focuses on a reduced feature set
# to explore feature importance
features:
  features_to_use:
    - "island_encoded"
    - "sex_encoded"
    - "culmen_length_mm"
    - "culmen_depth_mm"
  normalize: true

model:
  model_type: "random_forest"
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42

evaluation:
  # Include more metrics for better analysis
  metrics: ["accuracy", "precision", "recall", "f1", "roc_auc"]
  average: "macro"

split:
  test_ratio: 0.25
  validation_ratio: 0.0
  random_seed: 42

experiment:
  experiment_name: "penguin_feature_exploration"
  run_name: "reduced_feature_set"